CREATE TABLE students
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    updated_by         BIGINT,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    deleted            BOOLEAN,
    student_full_name  VARCHAR(255),
    birth_date         date,
    gender             VARCHAR(255),
    guardian_full_name VARCHAR(255),
    guardian_type      VARCHAR(255),
    guardianjshshir    VARCHAR(255),
    passport_id        VARCHAR(255),
    passport_issued_by VARCHAR(255),
    phone1             VARCHAR(255),
    phone2             VARCHAR(255),
    address            VARCHAR(255),
    comment            VARCHAR(255),
    amount             DOUBLE PRECISION,
    bcn                VARCHAR(255),
    grade_id           BIGINT,
    student_status     VARCHAR(255),
    CONSTRAINT pk_students PRIMARY KEY (id)
);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_GRADE FOREIGN KEY (grade_id) REFERENCES student_grades (id);