CREATE TABLE student_grades
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted    BOOLEAN,
    name       VARCHAR(255)
);