CREATE TABLE ads_assignment
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by      UUID,
    updated_by      UUID,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    placement_id    BIGINT                                  NOT NULL,
    campaign_id     BIGINT                                  NOT NULL,
    creative_id     BIGINT                                  NOT NULL,
    weight          INTEGER,
    lang_filter     JSONB,
    category_filter JSONB,
    start_at        TIMESTAMP WITHOUT TIME ZONE,
    end_at          TIMESTAMP WITHOUT TIME ZONE,
    is_active       BOOLEAN,
    CONSTRAINT pk_ads_assignment PRIMARY KEY (id)
);

CREATE TABLE ads_campaign
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by            UUID,
    updated_by            UUID,
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    name                  VARCHAR(255)                            NOT NULL,
    advertiser            VARCHAR(255)                            NOT NULL,
    status                VARCHAR(255)                            NOT NULL,
    start_at              TIMESTAMP WITHOUT TIME ZONE,
    end_at                TIMESTAMP WITHOUT TIME ZONE,
    daily_cap_impressions INTEGER,
    daily_cap_clicks      INTEGER,
    CONSTRAINT pk_ads_campaign PRIMARY KEY (id)
);

CREATE TABLE ads_creative
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by     UUID,
    updated_by     UUID,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    campaign_id    BIGINT                                  NOT NULL,
    type           VARCHAR(255),
    landing_url    VARCHAR(1000),
    image_media_id BIGINT,
    html_snippet   TEXT,
    is_active      BOOLEAN,
    CONSTRAINT pk_ads_creative PRIMARY KEY (id)
);

CREATE TABLE ads_creative_translation
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  UUID,
    updated_by  UUID,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    creative_id BIGINT                                  NOT NULL,
    lang        VARCHAR(5)                              NOT NULL,
    title       VARCHAR(255),
    alt_text    VARCHAR(255),
    CONSTRAINT pk_ads_creative_translation PRIMARY KEY (id)
);

CREATE TABLE ads_placement
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  UUID,
    updated_by  UUID,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    code        VARCHAR(100)                            NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description TEXT,
    is_active   BOOLEAN,
    CONSTRAINT pk_ads_placement PRIMARY KEY (id)
);

CREATE TABLE category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by UUID,
    updated_by UUID,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    parent_id  BIGINT,
    is_active  BOOLEAN,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE category_translation
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  UUID,
    updated_by  UUID,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    category_id BIGINT                                  NOT NULL,
    lang        VARCHAR(5)                              NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    slug        VARCHAR(255)                            NOT NULL,
    description TEXT,
    CONSTRAINT pk_category_translation PRIMARY KEY (id)
);

CREATE TABLE media
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  UUID,
    updated_by  UUID,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    storage_key VARCHAR(500)                            NOT NULL,
    url         VARCHAR(1000)                           NOT NULL,
    mime_type   VARCHAR(100),
    size        BIGINT,
    width       INTEGER,
    height      INTEGER,
    owner_id    UUID,
    is_public   BOOLEAN,
    CONSTRAINT pk_media PRIMARY KEY (id)
);

CREATE TABLE news
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by     UUID,
    updated_by     UUID,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    author_id      UUID                                    NOT NULL,
    category_id    BIGINT,
    cover_media_id BIGINT,
    status         VARCHAR(255)                            NOT NULL,
    is_featured    BOOLEAN,
    is_deleted     BOOLEAN,
    publish_at     TIMESTAMP WITHOUT TIME ZONE,
    unpublish_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_news PRIMARY KEY (id)
);

CREATE TABLE news_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  UUID,
    updated_by  UUID,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    news_id     BIGINT                                  NOT NULL,
    changed_by  UUID                                    NOT NULL,
    from_status VARCHAR(20),
    to_status   VARCHAR(20)                             NOT NULL,
    diff_json   JSONB,
    CONSTRAINT pk_news_history PRIMARY KEY (id)
);

CREATE TABLE news_tag
(
    news_id BIGINT NOT NULL,
    tag_id  BIGINT NOT NULL,
    CONSTRAINT pk_news_tag PRIMARY KEY (news_id, tag_id)
);

CREATE TABLE news_translation
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by       UUID,
    updated_by       UUID,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    news_id          BIGINT                                  NOT NULL,
    lang             VARCHAR(5)                              NOT NULL,
    title            VARCHAR(500)                            NOT NULL,
    slug             VARCHAR(500)                            NOT NULL,
    summary          TEXT,
    content          TEXT,
    meta_title       VARCHAR(255),
    meta_description TEXT,
    CONSTRAINT pk_news_translation PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by UUID,
    updated_by UUID,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    deleted    BOOLEAN,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE tag
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by UUID,
    updated_by UUID,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    code       VARCHAR(100)                            NOT NULL,
    is_active  BOOLEAN,
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id UUID   NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id            UUID         NOT NULL,
    created_by    UUID,
    updated_by    UUID,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    username      VARCHAR(50)  NOT NULL,
    email         VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active     BOOLEAN,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE category_translation
    ADD CONSTRAINT uc_54a965bfce81b418e2350c62b UNIQUE (slug, lang);

ALTER TABLE news_translation
    ADD CONSTRAINT uc_5efb572943656c689d27d7e41 UNIQUE (slug, lang);

ALTER TABLE category_translation
    ADD CONSTRAINT uc_72946ae741670b6095718bce7 UNIQUE (category_id, lang);

ALTER TABLE ads_creative_translation
    ADD CONSTRAINT uc_832075310992a291c56a922fd UNIQUE (creative_id, lang);

ALTER TABLE ads_placement
    ADD CONSTRAINT uc_ads_placement_code UNIQUE (code);

ALTER TABLE news_translation
    ADD CONSTRAINT uc_ff7f1b4f77c6937118c1504d9 UNIQUE (news_id, lang);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE tag
    ADD CONSTRAINT uc_tag_code UNIQUE (code);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE ads_assignment
    ADD CONSTRAINT FK_ADS_ASSIGNMENT_ON_CAMPAIGN FOREIGN KEY (campaign_id) REFERENCES ads_campaign (id);

ALTER TABLE ads_assignment
    ADD CONSTRAINT FK_ADS_ASSIGNMENT_ON_CREATIVE FOREIGN KEY (creative_id) REFERENCES ads_creative (id);

ALTER TABLE ads_assignment
    ADD CONSTRAINT FK_ADS_ASSIGNMENT_ON_PLACEMENT FOREIGN KEY (placement_id) REFERENCES ads_placement (id);

ALTER TABLE ads_creative
    ADD CONSTRAINT FK_ADS_CREATIVE_ON_CAMPAIGN FOREIGN KEY (campaign_id) REFERENCES ads_campaign (id);

ALTER TABLE ads_creative
    ADD CONSTRAINT FK_ADS_CREATIVE_ON_IMAGE_MEDIA FOREIGN KEY (image_media_id) REFERENCES media (id);

ALTER TABLE ads_creative_translation
    ADD CONSTRAINT FK_ADS_CREATIVE_TRANSLATION_ON_CREATIVE FOREIGN KEY (creative_id) REFERENCES ads_creative (id);

ALTER TABLE category
    ADD CONSTRAINT FK_CATEGORY_ON_PARENT FOREIGN KEY (parent_id) REFERENCES category (id);

ALTER TABLE category_translation
    ADD CONSTRAINT FK_CATEGORY_TRANSLATION_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE media
    ADD CONSTRAINT FK_MEDIA_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE news_history
    ADD CONSTRAINT FK_NEWS_HISTORY_ON_CHANGED_BY FOREIGN KEY (changed_by) REFERENCES users (id);

ALTER TABLE news_history
    ADD CONSTRAINT FK_NEWS_HISTORY_ON_NEWS FOREIGN KEY (news_id) REFERENCES news (id);

ALTER TABLE news
    ADD CONSTRAINT FK_NEWS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE news
    ADD CONSTRAINT FK_NEWS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE news
    ADD CONSTRAINT FK_NEWS_ON_COVER_MEDIA FOREIGN KEY (cover_media_id) REFERENCES media (id);

ALTER TABLE news_translation
    ADD CONSTRAINT FK_NEWS_TRANSLATION_ON_NEWS FOREIGN KEY (news_id) REFERENCES news (id);

ALTER TABLE news_tag
    ADD CONSTRAINT fk_news_tag_on_news FOREIGN KEY (news_id) REFERENCES news (id);

ALTER TABLE news_tag
    ADD CONSTRAINT fk_news_tag_on_tag FOREIGN KEY (tag_id) REFERENCES tag (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);